[project]
name = "llmailtest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "pandas>=2.1.0",
    "pyside6>=6.0.0",
    "pytest>=8.3.4",
    "python-dateutil>=2.8.2",
    "requests>=2.31.0",
]
